apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: audio-0725
  janus-idp.io/tekton: audio-0725
  backstage.io/kubernetes-id: audio-0725
  backstage.io/kubernetes-namespace: audio-0725 
  app.kubernetes.io/part-of: audio-0725
resources: 
- initialize-namespace.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml