kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: audio-0725-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: audio-0725-dsp-job
    namespace: audio-0725
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: audio-0725-dsp-job-role